"""Type stubs for tensorflow.keras for IDE resolution."""
from typing import Any, Callable, Dict, List, Optional, Union

class backend:
    @staticmethod
    def set_value(x: Any, value: Any) -> None: ...
    @staticmethod
    def get_value(x: Any) -> Any: ...

class Callback:
    def __init__(self) -> None: ...
    def on_batch_begin(self, batch: int, logs: Optional[Dict[str, Any]] = None) -> None: ...
    def on_batch_end(self, batch: int, logs: Optional[Dict[str, Any]] = None) -> None: ...
    def on_epoch_begin(self, epoch: int, logs: Optional[Dict[str, Any]] = None) -> None: ...
    def on_epoch_end(self, epoch: int, logs: Optional[Dict[str, Any]] = None) -> None: ...
    def on_train_begin(self, logs: Optional[Dict[str, Any]] = None) -> None: ...
    def on_train_end(self, logs: Optional[Dict[str, Any]] = None) -> None: ...
    
    model: Any
    validation_data: Any 